/*
 * Copyright 2025 Christian Kierdorf
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 */
package de.schliweb.makeacopy.anchor;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assume.assumeTrue;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import org.junit.Test;

/**
 * Schema/fidelity check for the REAL bundled verse-count table at
 * {@code app/src/main/assets/anchor/verse_counts.json} (slice F3b).
 *
 * <p>This table is generated by {@code tools/generate_verse_counts} on Kris's LAN against Concord and
 * committed by Kris — it is not present when the rest of F3b is first authored. Until it lands, this
 * test is <strong>skipped</strong> (via {@link org.junit.Assume}) rather than failed, so the suite is
 * green at the PR's stop point. A <em>skipped</em> result is the signal that the table is not yet in;
 * once committed, this test runs and enforces the schema.
 */
public class VerseCountsSchemaTest {

  private static final String[] CANDIDATE_PATHS = {
    "src/main/assets/anchor/verse_counts.json", // unit-test working dir = module (app/)
    "app/src/main/assets/anchor/verse_counts.json", // fallback if run from repo root
  };

  private static File locateRealTable() {
    for (String p : CANDIDATE_PATHS) {
      File f = new File(p);
      if (f.isFile()) return f;
    }
    return null;
  }

  @Test
  public void realTable_matchesBookMapAndSchema() throws IOException {
    File f = locateRealTable();
    assumeTrue(
        "verse_counts.json not committed yet — run tools/generate_verse_counts and commit it",
        f != null);

    String json = new String(Files.readAllBytes(f.toPath()), StandardCharsets.UTF_8);
    JsonObject root = JsonParser.parseString(json).getAsJsonObject();

    // meta: all four fields present, book_count == 66.
    JsonObject meta = root.getAsJsonObject("meta");
    assertNotNull("meta missing", meta);
    assertTrue("meta.source_translation missing", meta.has("source_translation"));
    assertTrue("meta.concord_version missing", meta.has("concord_version"));
    assertTrue("meta.generated_at missing", meta.has("generated_at"));
    assertEquals("meta.book_count", 66, meta.get("book_count").getAsInt());

    // books: keys exactly the 66 USFM codes from BookMap; every count a positive int.
    JsonObject books = root.getAsJsonObject("books");
    assertNotNull("books missing", books);

    Set<String> expected = new HashSet<>(BookMap.asMap().values());
    assertEquals("BookMap must define 66 USFM codes", 66, expected.size());
    assertEquals("table must contain exactly the 66 BookMap USFM codes", expected, books.keySet());

    for (Map.Entry<String, com.google.gson.JsonElement> e : books.entrySet()) {
      JsonArray arr = e.getValue().getAsJsonArray();
      assertTrue(e.getKey() + " has no chapters", arr.size() >= 1);
      for (int i = 0; i < arr.size(); i++) {
        int count = arr.get(i).getAsInt();
        assertTrue(
            e.getKey() + " chapter " + (i + 1) + " has non-positive verse count: " + count,
            count > 0);
      }
    }

    // Loadable by the production parser, and its book set matches.
    VerseTable table = VerseTable.fromJson(json);
    assertEquals(expected, new HashSet<>(table.bookCodes()));
  }
}
