ort:
  analyzer:
    skipExcluded: true
    disabledPackageManagers:
      - SBT
      - CocoaPods
      - PIP
      - NuGet
      - Bazel
  scanner:
    skipExcluded: true
    config:
      ScanCode:
        options:
          commandLineNonConfig: "--processes, 4"
  packageConfigurationProviders:
    - type: Dir
      options:
        path: ort/config/package-configurations
        mustExist: false
